name: coverage

on: [push]

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create Build Dir
        # CI Fails if we don't create the build dir
        run: mkdir build
      - name: Update packages
        run: apt update
      - name: Install dependencies
        run: apt install -y libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      - name: Generate code coverage
        working-directory: ./src-tauri
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --out xml
      - name: Workaround for codecov/feedback#263
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
